In [7]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

In [8]:
df = pd.read_csv('../../datasets/mp_ONS_decsriptors_v3.csv')

In [9]:
df.head()

,smiles,mp,ALogp2,AMR,apol,naAromAtom,nAromBond,nAtom,nHeavyAtom,nH,...,AMW,WTPT-1,WTPT-2,WTPT-3,WTPT-4,WTPT-5,WPATH,WPOL,XLogP,Zagreb
0,C1(CCC1)C,-161.5050,0.127164,20.3505,15.467930,0,0,15,5,10,...,4.671883,9.414511,1.882902,0.000000,0.0,0.000000,16,1,2.784,22
1,CN(C)C,-117.0400,0.102464,19.9881,12.381137,0,0,13,4,9,...,4.544115,6.732051,1.683013,2.732051,0.0,2.732051,9,0,0.063,12
2,ClC(Cl)(Cl)Cl,-22.9875,12.849357,26.8490,10.480000,0,0,5,5,0,...,30.375082,8.500000,1.700000,9.000000,0.0,0.000000,16,0,2.864,20
3,C#C,-80.7500,0.882472,6.9650,4.853586,0,0,4,2,2,...,6.503913,3.000000,1.500000,0.000000,0.0,0.000000,1,0,0.418,2
4,C(=C(Cl)Cl)(C(Cl)(Cl)Cl)Cl,-72.9500,12.286427,46.2872,18.360000,0,0,9,9,0,...,27.312568,16.104985,1.789443,14.108974,0.0,0.000000,86,10,3.603,40